name: workflow-02
on: push
jobs:
    job-01:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v3
            - name : Setup Node Environment
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install depedencies
              run: npm ci
            - name: Run Test
              run: npm test